Development
balbazauras/Messuring-vault-v2 pull request #1
Opened 2022-10-09 09:11 UTC by balbazauras

2022-10-09 09:35 UTC, daiarn requested changes
Left few comments to fix

2022-10-09 09:35 UTC, daiarn commented on mysite/api/admin.py
> +# Register your models here.
can remove this file if not used

2022-10-09 09:35 UTC, daiarn commented on mysite/api/views.py
> +                                           )
you can just do:
```
filtered_data =  DataEntry.objects.filter(your filters here)
```

2022-10-09 09:35 UTC, daiarn commented on mysite/api/views.py
> +    #   item.date = item.date.strftime('%Y-%m-%dT%H:%M:%S.%f%z')
remove comments

2022-10-09 09:35 UTC, daiarn commented on mysite/mysite/settings.py
> +    os.path.join(BASE_DIR),  # ?????static?????????
want to remove that comments or still do not know what static files are?

2022-10-09 09:35 UTC, daiarn commented on mysite/mysite/settings.py
> +
empty line not needed

2022-10-09 09:35 UTC, daiarn commented on mysite/mysite/settings.py
> +
empty line not needed

2022-10-09 09:35 UTC, daiarn commented on mysite/mysite/urls.py
> +            {'document_root': settings.STATIC_ROOT}),
what `re_path` do?

2022-10-09 09:35 UTC, daiarn commented on mysite/service/migrations/0008_alter_dataentry_value.py
> +class Migration(migrations.Migration):
this migration is the same as `0010` you can migrate back to `0008` migration and delete `0009` and `0010` migrations

2022-10-09 09:35 UTC, daiarn commented on mysite/service/static/js/graph.js
> +    console.log(data);
remove logging

2022-10-09 09:35 UTC, daiarn commented on mysite/service/static/js/graph.js
> +    var items = [];
you should not user `var` instead use `let` and `const` probably `const` here?

2022-10-09 09:35 UTC, daiarn commented on mysite/service/static/js/graph.js
> +      items.push("<li id='" + key + "'>" + val + "</li>");
that is not how you should build html elements. This the [tutorial](https://www.makeuseof.com/jquery-create-element/)

2022-10-09 09:35 UTC, daiarn commented on mysite/service/urls.py
> +    path('delete_system/<str:pk>/', views.delete_system, name="delete_system"),
not sure if necessary but links shoud be with `-` so `create-system/` for example

2022-10-09 09:35 UTC, daiarn commented on mysite/service/views.py
> +    # get all data entrys from this sensor
comments here not really needed but you can keep it if you need them

2022-10-09 09:35 UTC, daiarn commented on mysite/service/views.py
> +    sensor_data = single_sensor.dataentry_set.all()
you can add `.order_by('-date')` here

2022-10-09 09:35 UTC, daiarn commented on mysite/service/views.py
> +            print('Printing POST:', request.POST)
remove print

2022-10-09 09:35 UTC, daiarn commented on mysite/service/views.py
> +            print('Printing POST:', request.POST)
remove print

2022-10-09 19:54 UTC, balbazauras commented on mysite/mysite/urls.py
> +            {'document_root': settings.STATIC_ROOT}),
These are not used anymore, followed tutorial which needed static files atm I dont need them

2022-10-10 05:49 UTC, daiarn requested changes
ONe question and please remove cache files from commits with git ignore

2022-10-10 05:49 UTC, daiarn commented on mysite/service/templates/service/system.html
> +        <a
is this ok?

2022-10-12 12:08 UTC, closed without merging